development:
    adapter: mysql
    database: stagegrade_dev
    pool: 5
    username: root
    password: 
    socket: /tmp/mysql.sock

test:
    adapter: mysql
    database: stagegrade_test
    pool: 5
    username: root
    password: 
    socket: /tmp/mysql.sock
    
production:
    adapter: mysql
    database: stagegrade
    pool: 5
    username: root
    password: 
    socket: /tmp/mysql.sock